name = "C3xy's Optimized TMC"
author = "C3xy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7aba9cc6b171f43a95b11c62a1d6a86ffdd21a9b07868ccd6a23b30f171a52d6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
