name = "C3xy's Optimized TMC"
author = "C3xy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2060557029d9749dd3f9c1eafd67748f742f0a22c035fd8adc5ee4c11597b752"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
